CREATE TABLE `FACULTAD` (
  `ID_FAC` integer PRIMARY KEY AUTO_INCREMENT,
  `NOM_FAC` varchar(255) UNIQUE NOT NULL,
  `SIG_FAC` varchar(255) UNIQUE NOT NULL,
  `LOG_FAC` varchar(255) UNIQUE NOT NULL
);

CREATE TABLE `CARRERA` (
  `ID_CAR` integer PRIMARY KEY AUTO_INCREMENT,
  `ID_FAC_PER` integer,
  `NOM_CAR` varchar(255) UNIQUE NOT NULL,
  `SIG_CAR` varchar(255) UNIQUE NOT NULL
);

CREATE TABLE `USUARIOS` (
  `ID_USU` integer PRIMARY KEY AUTO_INCREMENT,
  `ID_ROL_PER` integer,
  `ID_FAC_PER` integer,
  `ID_CAR_PER` integer,
  `NOM_USU` varchar(255) NOT NULL,
  `APE_USU` varchar(255) NOT NULL,
  `COR_USU` varchar(255) UNIQUE NOT NULL
);

CREATE TABLE `ROL` (
  `ID_ROL` integer PRIMARY KEY AUTO_INCREMENT,
  `NOM_ROL` VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE `DETALLE_EST_CAR` (
  `ID_CAR_PER` integer,
  `ID_EST_PER` integer
);

CREATE TABLE `ESTUDIANTE` (
  `ID_EST` integer PRIMARY KEY AUTO_INCREMENT,
  `CED_EST` varchar(10) UNIQUE NOT NULL,
  `NOM_EST` varchar(255) NOT NULL,
  `APE_EST` varchar(255) NOT NULL,
  `DIR_EST` varchar(255),
  `CEL_EST` varchar(10),
  `COR_EST` varchar(255) UNIQUE NOT NULL
);

CREATE TABLE `DETALLE_CAT_CAR` (
  `ID_CAR_PER` integer,
  `ID_CAT_PER` integer
);

CREATE TABLE `CATEGORIA` (
  `ID_CAT` integer PRIMARY KEY AUTO_INCREMENT,
  `NOM_CAT` varchar(255) NOT NULL
);

CREATE TABLE `DOCUMENTO` (
  `ID_DOC` integer PRIMARY KEY AUTO_INCREMENT,
  `ID_CAT_PER` integer,
  `ID_USU_PER` integer,
  `FEC_DOC` datetime NOT NULL,
  `DES_DOC` text,
  `URL_DOC` varchar(255)
);

ALTER TABLE `CARRERA` ADD FOREIGN KEY (`ID_FAC_PER`) REFERENCES `FACULTAD` (`ID_FAC`);

ALTER TABLE `USUARIOS` ADD FOREIGN KEY (`ID_ROL_PER`) REFERENCES `ROL` (`ID_ROL`);

ALTER TABLE `USUARIOS` ADD FOREIGN KEY (`ID_FAC_PER`) REFERENCES `FACULTAD` (`ID_FAC`);

ALTER TABLE `USUARIOS` ADD FOREIGN KEY (`ID_CAR_PER`) REFERENCES `CARRERA` (`ID_CAR`);

ALTER TABLE `DETALLE_EST_CAR` ADD FOREIGN KEY (`ID_EST_PER`) REFERENCES `ESTUDIANTE` (`ID_EST`);

ALTER TABLE `DETALLE_EST_CAR` ADD FOREIGN KEY (`ID_CAR_PER`) REFERENCES `CARRERA` (`ID_CAR`);

ALTER TABLE `DOCUMENTO` ADD FOREIGN KEY (`ID_USU_PER`) REFERENCES `USUARIOS` (`ID_USU`);

ALTER TABLE `DOCUMENTO` ADD FOREIGN KEY (`ID_CAT_PER`) REFERENCES `CATEGORIA` (`ID_CAT`);

ALTER TABLE `DETALLE_CAT_CAR` ADD FOREIGN KEY (`ID_CAT_PER`) REFERENCES `CATEGORIA` (`ID_CAT`);

ALTER TABLE `DETALLE_CAT_CAR` ADD FOREIGN KEY (`ID_CAR_PER`) REFERENCES `CARRERA` (`ID_CAR`);
